# Gradle
org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.caching.debug=false
org.gradle.configureondemand=true
# Loom
fabric.loom.multiProjectOptimisation=true
# Mod Metadata
group=net.modfest
user=ModFest
slug=scattered-shards
modName=Scattered Shards
modDescription=Collectible trading cards... without the trading. Shards!
authors=Falkreon, acikek
contributors=Trudle, Tomate0613, afamiliarquiet, FoundationGames, TheEpicBlock, hama
license=MIT
# Mod Version
baseVersion=1.9.2
# Branch Metadata
branch=1.21.7
tagBranch=1.21.7
compatibleVersions= 1.21.7
compatibleLoaders=fabric, quilt, neoforge
